[package]
name = "mini_app_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
deadpool-diesel = {version = "0.6.1", features = ["postgres"] }
diesel = "2.2.3"
dotenvy = "0.15.7"
serde = "1.0.209"
tokio = { version = "1.39.3" , features = ["full"] }
